server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentmanager?setUnicode=true&characterEncoding=utf8&useAffetedRows=true
    username: root
    password: 123456
#  servlet:
#    multipart:
#      max-file-size: 30Mb
#      max-request-size: 30Mb
mybatis:
  type-aliases-package: com.example.student.domain
  mapper-locations: classpath:mapper/*.xml